<?php

/**
 * @file
 * Contains islandora_csl.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\islandora_csl\Encoder\CslEncoder;
use Seboettg\CiteProc\StyleSheet;
use Seboettg\CiteProc\CiteProc;

/**
 * Implements hook_theme().
 */
function islandora_csl_theme() {
  return [
    'csl' => [
      'variables' => [
        'csl' => NULL,
        'title' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function islandora_csl_entity_extra_field_info() {
  $extra_field = [];
  $bundles = [
    // entity_type => [bundle1, bundle2].
    'node' => [
      'islandora_object',
    ],
  ];
  foreach ($bundles as $entity_type => $bundles) {
    foreach ($bundles as $bundle) {
      $extra_field[$entity_type][$bundle]['display']['field_islandora_csl'] = [
        'label' => t('Citation'),
        'description' => t('The generated citation'),
        'weight' => 100,
        'visible' => TRUE,
      ];
    }
  }

  return $extra_field;
}

/**
 * Implements hook_entity_view().
 */
function islandora_csl_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $route_match_item = \Drupal::routeMatch()->getParameters()->get($entity->getEntityTypeId());
  // Ensure the entity matches the route.
  if ($entity === $route_match_item) {
    // @todo if you want other bundles than islandora object, check that here.
    if ($entity->bundle() == 'islandora_object'
      && $display->getComponent('field_islandora_csl')) {
      $entity_array = $entity->toArray();
      $encoder = \Drupal::service('islandora_csl.encoder');
      $csl_str = $encoder->encode($entity_array);
      $csl = [json_decode($csl_str)];

      $style = StyleSheet::loadStyleSheet("modern-language-association");
      $citeProc = new CiteProc($style);
      $mla = $citeProc->render($csl, "bibliography");

      $build['field_islandora_csl'] = [
        '#theme' => 'csl',
        '#title' => "Citation",
        '#csl' => $mla,
      ];
    }
  }
}
